/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ticket.booking;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class AppTest {
    @Test
    public void appProvidesCorsConfigurer() {
        App classUnderTest = new App();
        assertNotNull("app should provide CORS configuration", classUnderTest.corsConfigurer());
    }
}
